// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACTYR9IJIGIunV4wgJno51VswWFFfYF5I',
    appId: '1:506650756820:web:6424ce2f20991ca3b75d41',
    messagingSenderId: '506650756820',
    projectId: 'reminder-notes-b6b05',
    authDomain: 'reminder-notes-b6b05.firebaseapp.com',
    storageBucket: 'reminder-notes-b6b05.firebasestorage.app',
    measurementId: 'G-4VM78QTY3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5c2c7Yv00AAnUVR8M8XqWQSqqVxiR6Zk',
    appId: '1:506650756820:android:95943e529f56868fb75d41',
    messagingSenderId: '506650756820',
    projectId: 'reminder-notes-b6b05',
    storageBucket: 'reminder-notes-b6b05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbO42Y-mP65Oj7-eRVqq26CwN9MfPNijA',
    appId: '1:506650756820:ios:e1602366db1f96fbb75d41',
    messagingSenderId: '506650756820',
    projectId: 'reminder-notes-b6b05',
    storageBucket: 'reminder-notes-b6b05.firebasestorage.app',
    iosBundleId: 'com.practice.reminderNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbO42Y-mP65Oj7-eRVqq26CwN9MfPNijA',
    appId: '1:506650756820:ios:e1602366db1f96fbb75d41',
    messagingSenderId: '506650756820',
    projectId: 'reminder-notes-b6b05',
    storageBucket: 'reminder-notes-b6b05.firebasestorage.app',
    iosBundleId: 'com.practice.reminderNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACTYR9IJIGIunV4wgJno51VswWFFfYF5I',
    appId: '1:506650756820:web:3a9fae79e981ffd6b75d41',
    messagingSenderId: '506650756820',
    projectId: 'reminder-notes-b6b05',
    authDomain: 'reminder-notes-b6b05.firebaseapp.com',
    storageBucket: 'reminder-notes-b6b05.firebasestorage.app',
    measurementId: 'G-62J3ZDKPRH',
  );
}
